package se.axelkarlsson.hydroxide

const val DRAWER_SWIPE_DOWN_ANIMATION_DURATION_MILLIS = 300
const val DRAWER_SWIPE_DOWN_THRESHOLD_PIXELS = 30

const val APP_ICON_DEFAULT_ROUNDEDNESS = 0.18f
const val APP_ICON_DEFAULT_FOREGROUND_SCALING = 1.4f